# Writer Service CI Pipeline
# Maven build + Docker build

trigger:
- cicd  # writerregistration 용 브랜치 이름

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerfilePath: '$(Build.SourcesDirectory)/writerregistration/Dockerfile'
  buildContext: '$(Build.SourcesDirectory)/writerregistration'

stages:
- stage: Build
  displayName: Maven build + Docker image
  jobs:
  - job: Build
    displayName: Maven package + Docker build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: Maven@4  # ✅ 최신 버전
      displayName: 'Build jar with Maven'
      inputs:
        mavenPomFile: 'writerregistration/pom.xml'
        goals: 'package'
        options: '-B -Dmaven.test.skip=true'  # ✅ -B 옵션 추가
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        buildContext: $(buildContext)
        tags: |
          $(tag)
