version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: my-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka:29092,PLAINTEXT_HOST://my-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  writerregistration:
    build:
      context: ./writerregistration
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  subscriptionandpoint:
    build:
      context: ./subscriptionandpoint
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  bookpublication:
    build:
      context: ./bookpublication
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  aibookautomation:
    build:
      context: ./aibookautomation
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      