apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibookautomation
  labels:
    app: aibookautomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibookautomation
  template:
    metadata:
      labels:
        app: aibookautomation
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: aibookautomation
          image: "choitaehwan/aibookautomation:250703"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
