apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibookautomation
  labels:
    app: aibookautomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibookautomation
  template:
    metadata:
      labels:
        app: aibookautomation
    spec:
      containers:
        - name: aibookautomation
          image: "illilili/aipub-ai:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY