apiVersion: apps/v1
kind: Deployment
metadata:
  name: writerregistration
  labels:
    app: writerregistration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writerregistration
  template:
    metadata:
      labels:
        app: writerregistration
    spec:
      containers:
        - name: writerregistration
          image: "illilili/writerregistration:v3"
          imagePullPolicy: Always 
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
