# 기본 포트 설정 (로컬 또는 클러스터 외부 접속 시)
server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      httpclient:
        max-request-size: 10485760 # 10MB

      routes:
        - id: writerregistration
          uri: http://writerregistration:8080
          predicates:
            - Path=/writers/**, /admin/**, /writer-candidates/**
        - id: subscriptionandpoint
          uri: http://subscriptionandpoint:8080
          predicates:
            - Path=/users/**, /points/**, /subscriptions/**
        - id: bookpublication
          uri: http://bookpublication:8080
          predicates:
            - Path=/books/**
        - id: aibookautomation
          uri: http://aibookautomation:8080
          predicates:
            - Path=/aiBookProcessors/**
        - id: frontend
          uri: http://frontend:3000
          predicates:
            - Path=/**
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["*"]
            allowedMethods: ["*"]
            allowedHeaders: ["*"]
            allowCredentials: true

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: writerregistration
          uri: http://writerregistration:8080
          predicates:
            - Path=/writers/**, /admin/**, /writer-candidates/**
        - id: subscriptionandpoint
          uri: http://subscriptionandpoint:8080
          predicates:
            - Path=/users/**, /points/**, /subscriptions/**
        - id: bookpublication
          uri: http://bookpublication:8080
          predicates:
            - Path=/books/**
        - id: aibookautomation
          uri: http://aibookautomation:8080
          predicates:
            - Path=/aiBookProcessors/**
        - id: frontend
          uri: http://frontend:3000
          predicates:
            - Path=/**
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

# 도커 환경에서도 명시적으로 포트 지정
server:
  port: 8080
