apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptionandpoint
  labels:
    app: subscriptionandpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptionandpoint
  template:
    metadata:
      labels:
        app: subscriptionandpoint
    spec:
      containers:
        - name: subscriptionandpoint
          image: "illilili/aipub-subpoint:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
