apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
  labels:
    app: frontend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: frontend1
        image: choitaehwan/frontend1:250703  # 또는 ACR 이미지 경로로 수정
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5
